name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v4

      - name: Cache .npm
        uses: actions/cache@v4
        env:
          cache-name: cache-dot-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Check
        run: npm run check
